### ISSUE TITLE
Shorts the k8s context to cluster name instead full arn

### ISSUE THREAD

**Issue by danielrubin1989** [AdamRussak/k8f#11]
Write the cluster name instead of the full arn in the K8s context , makes the work with the contexts more intuitive

**Comment by AdamRussak** [comment]
will take care of it, but a bit of brain storming...

i thinking on leaving it as-is, and adding a flag to change output name.
so if default is:
arn:aws:eks:eu-central-1:<ID>:cluster/<Cluster name>

and flag will set it to:
552292662766:eu-central-1:animo-lt-eks

* I think the info here is helping, account,region,and cluster name

WDYT? @danielrubin1989

**Comment by AdamRussak** [comment]
another suggestion was made to do the following, 2 options (set by a flag):
1. account:region:eks_name
2. region:eks_name (default)

**Comment by AdamRussak** [comment]
resolved by PR #13 
and documentation updated to support new naming output for EKS clusters
