### ISSUE TITLE
version 0.5.11 AWS connection issue

### ISSUE THREAD

**Issue by ulielitay** [AdamRussak/k8f#17]
When running:
k8f connect aws --overwrite --short-name
k8f connect aws --overwrite 

i get the following error:

error Failed to get Describe Version: operation error EKS: DescribeAddonVersions, exceeded maximum number of attempts, 3, failed to sign request: failed to retrieve credentials: failed to refresh cached credentials, no EC2 IMDS role found, operation error ec2imds: GetMetadata, exceeded maximum number of attempts, 3, request send failed, Get "[http://169.254.169.254/latest/meta-data/iam/security-credentials/":](http://169.254.169.254/latest/meta-data/iam/security-credentials/%22:) dial tcp 169.254.169.254:80: connect: connection refused

Tested older version and they worked well.

**Comment by AdamRussak** [comment]
We need to add a pre-step for aws to validate configuration and credentials.

**Comment by AdamRussak** [comment]
after looking into it with @ulielitay , it looks like when creds and assume role are configured it takes both.
i need to add a check and validation for what creds to use.

**Comment by AdamRussak** [comment]
still need to update the options for creds or dyamic/ preferly dynamic

**Comment by AdamRussak** [comment]
solved in PR #24
